import {
  LayoutDashboard,
  Monitor,
  Wrench,
  CalendarDays,
  FileText,
  ClipboardList,
  Camera,
  Settings,
  MoreHorizontal,
  ChevronLeft,
  Home,
  Sun,
  Moon,
  Search,
  X,
  Plus,
  Filter,
  AlertTriangle,
  Package,
  PenLine,
  Trash2,
  Minus,
  Check,
  CircleDot,
  Clock,
  Calendar,
  FileBarChart,
  QrCode,
  ScanBarcode,
  FolderOpen,
  Inbox,
  RefreshCw,
  PlusCircle,
  HardDrive,
  Tag,
  BrushCleaning,
  Paperclip,
  Plug,
  Link2,
  PartyPopper,
  Scan,
  FlaskConical,
  CheckCircle,
  Focus,
  Cloud,
  CloudOff,
  CloudCheck,
  AlertCircle,
  WifiOff,
  User,
  UserCheck,
  Cable,
  Download,
  Upload,
  Printer,
  SlidersHorizontal,
  Copy,
  ChevronDown,
  Tv,
} from 'lucide-react'

export const icons = {
  nav: {
    dashboard: LayoutDashboard,
    pcs: Monitor,
    parts: Wrench,
    maintenance: CalendarDays,
    reports: FileText,
    checklists: ClipboardList,
    scanner: Camera,
    settings: Settings,
    more: MoreHorizontal,
  },
  ui: {
    back: ChevronLeft,
    home: Home,
    sun: Sun,
    moon: Moon,
    search: Search,
    close: X,
    plus: Plus,
    filter: Filter,
    check: Check,
    dot: CircleDot,
    clock: Clock,
    alertTriangle: AlertTriangle,
    package: Package,
    edit: PenLine,
    trash: Trash2,
    minus: Minus,
    moreHorizontal: MoreHorizontal,
    fileBarChart: FileBarChart,
    qrCode: QrCode,
    scanBarcode: ScanBarcode,
    folder: FolderOpen,
    inbox: Inbox,
    calendar: Calendar,
    refresh: RefreshCw,
    plusCircle: PlusCircle,
    hardDrive: HardDrive,
    tag: Tag,
    brushCleaning: BrushCleaning,
    paperclip: Paperclip,
    plug: Plug,
    link: Link2,
    partyPopper: PartyPopper,
    scan: Scan,
    flaskConical: FlaskConical,
    checkCircle: CheckCircle,
    focus: Focus,
    focusActive: Focus,
    cloud: Cloud,
    cloudOff: CloudOff,
    cloudCheck: CloudCheck,
    alertCircle: AlertCircle,
    wifiOff: WifiOff,
    user: User,
    userCheck: UserCheck,
    cable: Cable,
    download: Download,
    upload: Upload,
    printer: Printer,
    camera: Camera,
    sliders: SlidersHorizontal,
    copy: Copy,
    chevronDown: ChevronDown,
    alert: AlertTriangle,
    tv: Tv,
  },
} as const

export type NavIcon = keyof typeof icons.nav
export type UIIcon = keyof typeof icons.ui
