import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useAssets } from '../hooks/useAssets'
import type { AssetFormData, AssetStatus, Architecture, EquipmentType, OperatingSystem, StorageType } from '../types'
import { ARCHITECTURE_LABELS, ASSET_STATUS_LABELS, emptyNetworkInfo, emptyTechnicalInfo, EQUIPMENT_TYPES, OPERATING_SYSTEM_LABELS, STORAGE_TYPE_LABELS } from '../types'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../../lib/components/ui'

const emptyForm = (): AssetFormData => ({ assetTag: '', equipmentType: 'Desktop', manufacturer: '', model: '', serialNumber: '', location: '', status: 'available', observations: '', technical: emptyTechnicalInfo(), network: emptyNetworkInfo(), parentAssetId: null, childAssetIds: [], photos: [] })
const inputClass = 'w-full rounded-lg border border-line bg-card px-3 py-2 text-sm text-fg outline-none focus:border-violet-500'
export function PCForm() {
  const { id } = useParams(); const navigate = useNavigate(); const { assets, create, update } = useAssets(); const asset = assets.find((item) => item.id === id); const [form, setForm] = useState<AssetFormData>(emptyForm())
  useEffect(() => { if (asset) { const { id: _id, createdAt: _createdAt, updatedAt: _updatedAt, ...data } = asset; setForm(data) } }, [asset])
  const isNew = !id
  const set = <K extends keyof AssetFormData>(key: K, value: AssetFormData[K]) => setForm((current) => ({ ...current, [key]: value }))
  const technical = <K extends keyof AssetFormData['technical']>(key: K, value: AssetFormData['technical'][K]) => setForm((current) => ({ ...current, technical: { ...current.technical, [key]: value } }))
  const network = <K extends keyof AssetFormData['network']>(key: K, value: AssetFormData['network'][K]) => setForm((current) => ({ ...current, network: { ...current.network, [key]: value } }))
  function submit(event: React.FormEvent) { event.preventDefault(); const now = new Date().toISOString(); if (isNew) { const saved = create({ ...form, createdAt: now, updatedAt: now }); navigate(`/pc-care/assets/${saved.id}`) } else { update(id!, { ...form, updatedAt: now }); navigate(`/pc-care/assets/${id}`) } }
  if (!isNew && !asset) return <p className="py-12 text-center text-sm text-fg-muted">Ativo não encontrado.</p>
  return <div><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-semibold">{isNew ? 'Novo ativo' : 'Editar ativo'}</h2><p className="text-xs text-fg-muted">Campos com * são obrigatórios.</p></div><button type="button" onClick={() => navigate(-1)} className="text-sm text-fg-muted">Voltar</button></div>
    <form onSubmit={submit} className="space-y-4">
      <Section title="Identificação"><div className="grid gap-3 sm:grid-cols-2"><Field label="Patrimônio *"><input required value={form.assetTag} onChange={(e) => set('assetTag', e.target.value)} className={inputClass} /></Field><Field label="Tipo do equipamento *"><Select value={form.equipmentType} onValueChange={(value) => set('equipmentType', value as EquipmentType)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{EQUIPMENT_TYPES.map((type) => <SelectItem key={type} value={type}>{type}</SelectItem>)}</SelectContent></Select></Field><Field label="Fabricante *"><input required value={form.manufacturer} onChange={(e) => set('manufacturer', e.target.value)} className={inputClass} /></Field><Field label="Modelo *"><input required value={form.model} onChange={(e) => set('model', e.target.value)} className={inputClass} /></Field><Field label="Número de série *"><input required value={form.serialNumber} onChange={(e) => set('serialNumber', e.target.value)} className={inputClass} /></Field><Field label="Localização *"><input required value={form.location} onChange={(e) => set('location', e.target.value)} className={inputClass} /></Field><Field label="Status *"><Select value={form.status} onValueChange={(value) => set('status', value as AssetStatus)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(ASSET_STATUS_LABELS).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field></div></Section>
      <Section title="Informações técnicas"><div className="grid gap-3 sm:grid-cols-2"><Field label="Sistema operacional"><Select value={form.technical.operatingSystem} onValueChange={(value) => technical('operatingSystem', value as OperatingSystem)}><SelectTrigger><SelectValue placeholder="Não informado" /></SelectTrigger><SelectContent><SelectItem value="none">Sem SO</SelectItem>{Object.entries(OPERATING_SYSTEM_LABELS).filter(([value]) => value !== 'none').map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field><Field label="Arquitetura"><Select value={form.technical.architecture} onValueChange={(value) => technical('architecture', value as Architecture)}><SelectTrigger><SelectValue placeholder="Não informado" /></SelectTrigger><SelectContent>{Object.entries(ARCHITECTURE_LABELS).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field><Field label="Processador"><input value={form.technical.processor} onChange={(e) => technical('processor', e.target.value)} placeholder="Ex: Apple M3" className={inputClass} /></Field><Field label="Memória RAM"><input value={form.technical.memory} onChange={(e) => technical('memory', e.target.value)} placeholder="Ex: 16 GB" className={inputClass} /></Field><Field label="Tipo de armazenamento"><Select value={form.technical.storageType} onValueChange={(value) => technical('storageType', value as StorageType)}><SelectTrigger><SelectValue placeholder="Não informado" /></SelectTrigger><SelectContent>{Object.entries(STORAGE_TYPE_LABELS).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field><Field label="Capacidade"><input value={form.technical.storageCapacity} onChange={(e) => technical('storageCapacity', e.target.value)} placeholder="Ex: 512 GB" className={inputClass} /></Field><Field label="Marca do armazenamento"><input value={form.technical.storageBrand} onChange={(e) => technical('storageBrand', e.target.value)} className={inputClass} /></Field></div></Section>
      <Section title="Rede"><div className="grid gap-3 sm:grid-cols-2"><Field label="Hostname"><input value={form.network.hostname} onChange={(e) => network('hostname', e.target.value)} className={inputClass} /></Field><Field label="IP"><input value={form.network.ip} onChange={(e) => network('ip', e.target.value)} className={inputClass} /></Field><Field label="MAC Ethernet"><input value={form.network.macEthernet} onChange={(e) => network('macEthernet', e.target.value)} className={inputClass} /></Field><Field label="MAC Wi-Fi"><input value={form.network.macWifi} onChange={(e) => network('macWifi', e.target.value)} className={inputClass} /></Field><Field label="Domínio"><input value={form.network.domain} onChange={(e) => network('domain', e.target.value)} className={inputClass} /></Field></div></Section>
      <Section title="Observações"><textarea required value={form.observations} onChange={(e) => set('observations', e.target.value)} rows={4} className={inputClass} /></Section>
      <div className="flex gap-3"><button type="button" onClick={() => navigate(-1)} className="flex-1 rounded-lg border border-line py-2 text-sm">Cancelar</button><button className="flex-1 rounded-lg bg-violet-600 py-2 text-sm font-medium text-white">Salvar ativo</button></div>
    </form></div>
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-line bg-card/50 p-4"><h3 className="mb-3 text-xs font-semibold uppercase tracking-wider text-fg-muted">{title}</h3>{children}</section> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs text-fg-muted"><span className="mb-1 block">{label}</span>{children}</label> }
